{{- if and .Values.runner.enabled .Values.runner.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.runner.serviceAccount.name }}
  labels:
    {{- include "talon.labels" . | nindent 4 }}
  {{- with .Values.runner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
